### ISSUE TITLE
Changeset breaks OSMCha

### ISSUE THREAD

**Issue by emersonveenstra** [OSMCha/osmcha-frontend#646]
## *Brief Description*
Changeset https://osmcha.org/changesets/132982621/ breaks OSMCha, it fails to load the map

## What  is the current behaviour, (attach relevant screenshots) ?
```
"TypeError: Cannot read properties of undefined (reading 'properties')
    at Jm (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:221594)
    at https://osmcha.org/static/js/3.18209c6b.chunk.js:2:221372
    at Bs.n.onclosetag (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:120664)
    at _ (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:115007)
    at x (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:115046)
    at P (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:118387)
    at n.write (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:107669)
    at Bs (https://osmcha.org/static/js/3.18209c6b.chunk.js:2:120710)
    at https://osmcha.org/static/js/3.18209c6b.chunk.js:2:221196
    at new Promise (<anonymous>)
    at https://osmcha.org/static/js/3.18209c6b.chunk.js:2:221169"
```

## What  is the expected behaviour ?
Display the changeset correctly

## How do we replicate the issue ?
1. Go to https://osmcha.org/changesets/132982621/

## Please tell us about your environment:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`

## Other Information / context:
Achavi displays it correctly, so it's not an issue with the Overpass output

**Comment by mukeshblackhat** [comment]
i would love to work on this issue , it could be great if you could guide me a bit about how to setup this project locally and run to achieve this error again .

**Comment by nrenner** [comment]
Duplicate of #646
